### ISSUE TITLE
Cannot compile on Ubuntu 20.04

### ISSUE THREAD

**Issue by iriki** [kscz/n_stress#3]
Actually it's Mint 20.2, but it's based on focal.

```
$ make
gcc -Wall -Werror -O2 -c n_stress.c -o n_stress.o
gcc -Wall -Werror -O2 -c packets.c -o packets.o
packets.c: In function ‘generate_packet’:
packets.c:118:53: error: division ‘sizeof (unsigned char *) / sizeof (unsigned char)’ does not compute the number of array elements [-Werror=sizeof-pointer-div]
  118 |     currentjunk= (currentjunk + 4) % (sizeof(buffer)/sizeof(*buffer));
      |                                                     ^
packets.c:92:36: note: first ‘sizeof’ operand was declared here
   92 | int generate_packet(unsigned char *buffer, size_t buffersize)
      |                     ~~~~~~~~~~~~~~~^~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:20: packets.o] Error 1
```

If I try to compile with -Wno-error :

```
$ make
gcc -Wall -Wno-error -O2 -c packets.c -o packets.o
packets.c: In function ‘generate_packet’:
packets.c:118:53: warning: division ‘sizeof (unsigned char *) / sizeof (unsigned char)’ does not compute the number of array elements [-Wsizeof-pointer-div]
  118 |     currentjunk= (currentjunk + 4) % (sizeof(buffer)/sizeof(*buffer));
      |                                                     ^
packets.c:92:36: note: first ‘sizeof’ operand was declared here
   92 | int generate_packet(unsigned char *buffer, size_t buffersize)
      |                     ~~~~~~~~~~~~~~~^~~~~~
gcc -Wall -Wno-error -O2 -c ccrc32.c -o ccrc32.o
gcc -Wall -Wno-error -lpthread -O2 -o n_stress *.o
/usr/bin/ld: n_stress.o: in function `main':
n_stress.c:(.text.startup+0x189): undefined reference to `pthread_create'
/usr/bin/ld: n_stress.c:(.text.startup+0x1ad): undefined reference to `pthread_join'
/usr/bin/ld: n_stress.c:(.text.startup+0x2c6): undefined reference to `pthread_create'
/usr/bin/ld: n_stress.c:(.text.startup+0x2df): undefined reference to `pthread_join'
/usr/bin/ld: n_stress.c:(.text.startup+0x406): undefined reference to `pthread_create'
/usr/bin/ld: n_stress.c:(.text.startup+0x41e): undefined reference to `pthread_join'
/usr/bin/ld: n_stress.c:(.text.startup+0x524): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make: *** [Makefile:18: n_stress] Error 1
```

Could you please help? Many thanks in advance.

**Comment by kscz** [comment]
Whew! That is a terrible bug which, in retrospect, is terribly obvious - I wrote this repository back when I was over-confident in my understanding of C semantics. The warning-as-error is completely correct! This code only works because my bug is symmetric!

I'll take some time and patch this up, but I'm probably going to do something close to a re-write to make it... less terrible.

**Comment by kscz** [comment]
This should be fixed by this commit - https://github.com/kscz/n_stress/commit/bfb011b69bc2b91f66b97556c5f77523c9bec3a3

I also fixed a whole host of small issues, but still need to devote more time to cleaning this up before I'd be fully happy with it. For now - it should compile and run unlike before! Please re-open this issue if you have any problems compiling.

**Comment by iriki** [comment]
Thanks, it compiles now. Much appreciated!
